name: Testing front- & backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1.1.0

    - name: Setup project
      run: | 
        cd frontend/
        npm install

    - name: Run tests using Jest
      run: | 
        cd frontend/
        npm run test
  
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Install MaritimeDataModel
      run: |
        cd backend/libs/MaritimeDataModel
        mvn -B install --file pom.xml
        
    - name: Run tests with Maven
      run: |
        cd backend/
        mvn -B test --file pom.xml
